// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-kvI34D-TrQx3WGdHaXIuxLZhxLgPxPs',
    appId: '1:476173602315:web:0b872d87edd8ee4d87810e',
    messagingSenderId: '476173602315',
    projectId: 'store-mgmnt-0001',
    authDomain: 'store-mgmnt-0001.firebaseapp.com',
    storageBucket: 'store-mgmnt-0001.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQAM7KgOCdwNhzNwQEpXmKYjQhHsx4iwI',
    appId: '1:476173602315:android:3573bee880d7f10287810e',
    messagingSenderId: '476173602315',
    projectId: 'store-mgmnt-0001',
    storageBucket: 'store-mgmnt-0001.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS9T2jZiprlXmOXStTLdfCFCeYcX_qfp0',
    appId: '1:476173602315:ios:dc235424d3f4ef6a87810e',
    messagingSenderId: '476173602315',
    projectId: 'store-mgmnt-0001',
    storageBucket: 'store-mgmnt-0001.appspot.com',
    iosBundleId: 'org.muler.ahmedadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-kvI34D-TrQx3WGdHaXIuxLZhxLgPxPs',
    appId: '1:476173602315:web:987a893a09b5894387810e',
    messagingSenderId: '476173602315',
    projectId: 'store-mgmnt-0001',
    authDomain: 'store-mgmnt-0001.firebaseapp.com',
    storageBucket: 'store-mgmnt-0001.appspot.com',
  );

}